/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mes2;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import static mes2.gaussC.gauss;

/**
 *
 * @author maciejwojcik
 */
public class Window extends javax.swing.JFrame {
    
    public static String filename;
    public static ArrayList<String> datalist = new ArrayList<>();
    public static int nh = 51;
    public static int ne = nh - 1;
    Chart ch = new Chart();
    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void initdata(Data d, Element[] el, Node[] n){

        
        double r = 0;
        double deltar = d.rmax / ne;
        
        for (int i = 0; i < nh; i++){
            double alfa = 0;
            if (i == ne) alfa = d.alfaair;
            
            n[i].temp = d.tempbegin;
            n[i].bcond = 2* alfa * d.rmax * d.tempair;
            n[i].r = r;
            n[i].alfa = alfa;
            //textArea.append(n[i].bcond + "\n");
            r += deltar;
        }
        
        for (int i = 0; i < ne; i++)
	{
		el[i].node1 = n[i];
		el[i].node2 = n[i + 1];
		el[i].c = d.c;
		el[i].ro = d.ro;
		el[i].k = d.k;
                //textArea.append(el[i].c + "\n");
	}    
    }
    
    public void initlocals(Element[] el, Node[] n, Data d){
        int np = 2;
        double[] N1 = {0.5 * (1 + 0.57735027), 0.5 * (1 - 0.57735027)};
        double[] N2 = {0.5 * (1 - 0.57735027), 0.5 * (1 + 0.57735027)};
        
        for (int i = 0; i < ne; i++){
            double deltar = el[i].node2.r - el[i].node1.r;
            double dr = d.rmax / ne;
            double dtau = (Math.pow(dr, 2)) / (0.5 * d.a);
            double ntime = (d.taumax / dtau) + 1;
            dtau = d.taumax / ntime;
            //textArea.append(el[i].node2.r + "\n");
            
            el[i].localH[0][0] = 0;
            el[i].localH[0][1] = 0;
            el[i].localH[1][0] = 0;
            el[i].localH[1][1] = 0;

            el[i].localP[0] = 0;
            el[i].localP[1] = 0;
            
            for (int ip = 0; ip < np; ip++){
                double rp = N1[ip] * el[i].node1.r + N2[ip] * el[i].node2.r;
                double q = el[i].ro * el[i].c * deltar / dtau;
                
                el[i].localH[0][0] += el[i].k / deltar * rp + q *(N1[ip] * N1[ip]) * rp;
		el[i].localH[0][1] += -el[i].k / deltar * rp + q *(N1[ip] * N2[ip]) * rp;
		el[i].localH[1][0] = el[i].localH[0][1];
		el[i].localH[1][1] += el[i].k / deltar * rp + q *(N2[ip] * N2[ip]) * rp;

		el[i].localP[0] += -q*(N1[ip] * el[i].node1.temp + N2[ip] * el[i].node2.temp) * N1[ip] * rp;
		el[i].localP[1] += -q*(N1[ip] * el[i].node1.temp + N2[ip] * el[i].node2.temp) * N2[ip] * rp;
                //textArea.append(q +"");
            }
            el[i].localH[1][1] += 2 * el[i].node2.alfa * el[i].node2.r;
            el[i].localP[1] -= el[i].node2.bcond;
            
            //textArea.append(el[i].localH[0][0] + "\t");
            //textArea.append(el[i].localH[0][1] + "\n");
            //textArea.append(el[i].localH[1][0] + "\t");
            //textArea.append(el[i].localH[1][1] + "\n\n");
            
        }  
    }
    
    public void initglobals(Element[] el, Node[] n, double[][] globalH, double[] globalP, Data d){
        for (int i = 0; i < nh; i++) {
		for (int j = 0; j < nh; j++) {
			globalH[i][j] = 0;   
		}
	}

	for (int i = 0; i < nh; i++) {
		globalP[i] = 0;
	}


	for (int i = 0; i < ne; i++) {
		globalH[i][i] += el[i].localH[0][0];
		globalH[i][i + 1] += el[i].localH[0][1];
		globalH[i + 1][i] += el[i].localH[1][0];
		globalH[i + 1][i + 1] += el[i].localH[1][1];

	}
	for (int i = 0; i < ne; i++) {
		globalP[i] += el[i].localP[0];
		globalP[i + 1] += el[i].localP[1];
	}
        
        /*
        for (int i = 0; i < nh; i++) {
		for (int j = 0; j < nh; j++) {
			textArea.append(globalH[i][j]+"\t");   
		}
                textArea.append("\n");
	}
        */
    }
    
    public void merge(double[][] matrix, double[][] globalH, double[] globalP){
        for (int i = 0; i < nh; i++) {
            for (int j = 0; j < nh; j++)
		matrix[i][j] = globalH[i][j];
            }   
        
        for (int i = 0; i < nh; i++)
		matrix[i][nh] = globalP[i];
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        calcButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        clearButton = new javax.swing.JButton();
        draftButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MES 2");
        setResizable(false);

        dataButton.setText("Wczytaj dane");
        dataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Wyjście");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Rmax");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("AlfaAir");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("TempBegin");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("TempAir");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setText("C");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("Ro");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setText("K");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setText("TauMax");

        calcButton.setText("Oblicz");
        calcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        clearButton.setText("Wyczyść");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        draftButton.setText("Rysuj wykres");
        draftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                draftButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(calcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(draftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(draftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void dataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        Scanner sc = null;
        try {
            sc = new Scanner(f);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }
        while (sc.hasNextLine()) {
            datalist.add(sc.nextLine());
        }

        String[] arr = datalist.toArray(new String[0]);
        //jTextField1.setText(arr[0]);
        jTextField2.setText(arr[0]);
        jTextField3.setText(arr[1]);
        jTextField4.setText(arr[2]);
        jTextField5.setText(arr[3]);
        jTextField6.setText(arr[4]);
        jTextField7.setText(arr[5]);
        jTextField8.setText(arr[6]);
        jTextField9.setText(arr[7]); 
        
        
        
    }//GEN-LAST:event_dataButtonActionPerformed

    private void calcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtonActionPerformed
        Data d = new Data();
        d.a = (Double.parseDouble(jTextField8.getText())) / (Double.parseDouble(jTextField6.getText()) * Double.parseDouble(jTextField7.getText()));
        d.rmax = Double.parseDouble(jTextField2.getText());
        d.taumax = Double.parseDouble(jTextField9.getText());
        d.k = Double.parseDouble(jTextField8.getText());
        d.tempbegin = Double.parseDouble(jTextField4.getText());
        d.tempair = Double.parseDouble(jTextField5.getText());
        d.alfaair = Double.parseDouble(jTextField3.getText());
        d.c = Double.parseDouble(jTextField6.getText());
        d.ro = Double.parseDouble(jTextField7.getText());
        Element[] el = new Element[ne];
        Node[] n = new Node[nh];
        for (int i = 0; i < ne; i++) el[i] = new Element();
        for (int i = 0; i < nh; i++) n[i] = new Node();
        double[][] globalH = new double[nh][nh];
        double[] globalP = new double[nh];
        double[] globalT = new double[nh];
        double[] globalPmin = new double[nh];
        double[][] matrix = new double[nh][nh + 1];
        double dr = d.rmax / ne;
        double dtau = (Math.pow(dr, 2)) / (0.5 * d.a);
        double ntime = (d.taumax / dtau) + 1;
        dtau = d.taumax / ntime;
       
        
        initdata(d, el, n);
        
        for (double time = 0; time <= d.taumax; time += dtau){
            initlocals(el, n, d);
            initglobals(el, n, globalH, globalP, d);
            
            for (int i = 0; i < nh; i++){
		globalPmin[i] = globalP[i] * (-1);
            }
            
            merge(matrix, globalH, globalPmin);
            gauss(nh, matrix, globalT);
            
            for (int i = 0; i < nh; i++)
		n[i].temp = globalT[i];
                
            textArea.append(time + "\t");
	    textArea.append(globalT[0] + "\t");
            textArea.append(globalT[ne] + "\n");
            //textArea.append("\n");
            
            
            ch.inputDataSet2(time,globalT[0]);
            ch.inputDataSet1(time,globalT[ne]);
        }
        
        
    }//GEN-LAST:event_calcButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        textArea.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void draftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_draftButtonActionPerformed
        ch.createwykres();
    }//GEN-LAST:event_draftButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton dataButton;
    private javax.swing.JButton draftButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField jTextField2;
    public static javax.swing.JTextField jTextField3;
    public static javax.swing.JTextField jTextField4;
    public static javax.swing.JTextField jTextField5;
    public static javax.swing.JTextField jTextField6;
    public static javax.swing.JTextField jTextField7;
    public static javax.swing.JTextField jTextField8;
    public static javax.swing.JTextField jTextField9;
    public static javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
